### ISSUE TITLE
Pass parameter from NewsViewController to Flutter

### ISSUE THREAD

**Issue by batkhishign55** [cosinus84/flutter-navigate-to-ios-view-controller#1]
Hi, I am new to ios dev, flutter dev and generally mobile dev. I was wondering what is the best way to pass parameter from NewsViewController. Let's say NewsViewController has two buttons, and depending on which button is pressed, different parameter is passed to Flutter. And by any chance is there a way to pass it using FlutterResult of FlutterMethodChannel to achieve this result?

Thank you in advance.

**Comment by cosinus84** [comment]
Hi, I think FlutterMethodChannel is to pass data from flutter to native and get a result from native. But you can use streams and have an "open" channel between flutter and ios.
https://medium.com/@igaurab/event-channels-in-flutter-2b4d0db0ee4f
Hope it helps

**Comment by batkhishign55** [comment]
I achieved the desired result using ios NotificationCenter.
First I added result variable in AppDelegate.swift that can be modifiable from view controllers:

```swift
var res: String = ""
```
Then I added a new observer on  method channel handler right after `self.mainCoordinator?.start().`, like so:
````swift
self?.observer = NotificationCenter.default.addObserver(forName: .kMyNotification, object:nil, queue: nil, using: {(note) in
                    self?.handleMyNotification(result: result)
````
handleMyNotification method:
```swift
 @objc func handleMyNotification(result: FlutterResult) {
        print("Notification received!")
        NotificationCenter.default.removeObserver(self.observer)
        result(self.res)
    }
```
The native view controller fires a notification on a button press event:
```swift
        self.appDelegate.res = result
        let nc = NotificationCenter.default
        nc.post(name: .kMyNotification, object: nil)
```
When the observer receives the notification, it uses handleMyNotification method to set the result for flutter method channel handler.

Thanks for the reply anyway. Closing this issue.
